package com.hpe.upi.npci.adapter;

import java.math.BigDecimal;
import java.time.Instant;

/**
 * NpciRequest — outbound message to the NPCI UPI network.
 *
 * After construction by NpciAdapterImpl, this object carries:
 *   - Core UPI fields (txnId, rrn, VPAs, amount, operation)
 *   - ISO 8583 encoding (bitmap + raw hex) — generated by Iso8583Codec
 *   - NPCI XML payload — generated by NpciXmlMapper
 *
 * In a real HPE NonStop deployment:
 *   - iso8583RawHex goes onto the bank leased line via KMSF
 *   - xmlPayload goes to NPCI switch via Pathway ServerClass
 */
public class NpciRequest {

    public enum OperationType { DEBIT, CREDIT, REVERSAL }

    // ── Core UPI fields ───────────────────────────────────────────────────────
    private String msgId;
    private String txnId;
    private String rrn;
    private String payerVpa;
    private String payeeVpa;
    private String payerBank;
    private String payeeBank;
    private String payerAccountNumber;
    private String payeeAccountNumber;
    private BigDecimal amount;
    private OperationType operation;
    private String reversalReason;
    private boolean simulateFailure;
    private Instant requestedAt;
    private String npciRoutingCode;

    // ── ISO 8583 fields (set by Iso8583Codec) ─────────────────────────────────
    private String iso8583Bitmap;   // 16-char hex bitmap (primary + secondary)
    private String iso8583RawHex;   // Full message hex — MTI + bitmap + data elements

    // ── NPCI XML payload (set by NpciXmlMapper) ────────────────────────────────
    private String xmlPayload;      // ReqPay / ReqCredit / ReqRvsl XML

    public NpciRequest() { this.requestedAt = Instant.now(); }

    // ── Getters and setters ───────────────────────────────────────────────────
    public String getMsgId() { return msgId; }
    public void setMsgId(String v) { this.msgId = v; }

    public String getTxnId() { return txnId; }
    public void setTxnId(String v) { this.txnId = v; }

    public String getRrn() { return rrn; }
    public void setRrn(String v) { this.rrn = v; }

    public String getPayerVpa() { return payerVpa; }
    public void setPayerVpa(String v) { this.payerVpa = v; }

    public String getPayeeVpa() { return payeeVpa; }
    public void setPayeeVpa(String v) { this.payeeVpa = v; }

    public String getPayerBank() { return payerBank; }
    public void setPayerBank(String v) { this.payerBank = v; }

    public String getPayeeBank() { return payeeBank; }
    public void setPayeeBank(String v) { this.payeeBank = v; }

    public String getPayerAccountNumber() { return payerAccountNumber; }
    public void setPayerAccountNumber(String v) { this.payerAccountNumber = v; }

    public String getPayeeAccountNumber() { return payeeAccountNumber; }
    public void setPayeeAccountNumber(String v) { this.payeeAccountNumber = v; }

    public BigDecimal getAmount() { return amount; }
    public void setAmount(BigDecimal v) { this.amount = v; }

    public OperationType getOperation() { return operation; }
    public void setOperation(OperationType v) { this.operation = v; }

    public String getReversalReason() { return reversalReason; }
    public void setReversalReason(String v) { this.reversalReason = v; }

    public boolean isSimulateFailure() { return simulateFailure; }
    public void setSimulateFailure(boolean v) { this.simulateFailure = v; }

    public Instant getRequestedAt() { return requestedAt; }
    public void setRequestedAt(Instant v) { this.requestedAt = v; }

    public String getNpciRoutingCode() { return npciRoutingCode; }
    public void setNpciRoutingCode(String v) { this.npciRoutingCode = v; }

    public String getIso8583Bitmap() { return iso8583Bitmap; }
    public void setIso8583Bitmap(String v) { this.iso8583Bitmap = v; }

    public String getIso8583RawHex() { return iso8583RawHex; }
    public void setIso8583RawHex(String v) { this.iso8583RawHex = v; }

    public String getXmlPayload() { return xmlPayload; }
    public void setXmlPayload(String v) { this.xmlPayload = v; }

    @Override
    public String toString() {
        return "NpciRequest{msgId=" + msgId
            + ", txnId=" + txnId
            + ", operation=" + operation
            + ", amount=₹" + amount
            + ", payer=" + payerVpa + "(" + payerAccountNumber + ")"
            + ", payee=" + payeeVpa + "(" + payeeAccountNumber + ")"
            + ", routingCode=" + npciRoutingCode
            + ", iso8583Bitmap=" + iso8583Bitmap + "}";
    }
}
