spring.datasource.url=jdbc:postgresql://localhost:5432/upi
spring.datasource.username=postgres
spring.datasource.password=qwerty.321

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=audit-group
spring.kafka.consumer.auto-offset-reset=earliest