spring.application.name=npci-ledger-service
spring.datasource.url=jdbc:postgresql://localhost:5432/upi
spring.datasource.username=postgres
spring.datasource.password=qwerty

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=npci-ledger-group
spring.kafka.consumer.auto-offset-reset=earliest

server.port=8086
